### ISSUE TITLE
Not found issue

### ISSUE THREAD

**Issue by landed1** [seanchas116/glob-loader#5]
Not sure if I am using this wrong ..

require('glob-loader!/src/css/_.css');
Module not found: Error: Cannot resolve 'file' or 'directory' ./src/css/_.css

So I am trying to require any css file in the src/css folder the path for me is correct because I can manually copy a css file using file-loader using the same path i.e.
require('file?name=css/hacks.css!src/css/hacks.css'); //this works file by file so the path is right - TY

**Comment by joscha** [comment]
@landed1 The target for the glob-loader is a file with a glob pattern in it, not the actual glob itself.
